name: Tests

on: push

jobs:
  test:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: cmake -B build-a -S a -DCMAKE_INSTALL_PREFIX=install
      - run: cmake --build build-a
      - run: cmake --build build-a -t test
      - run: cmake --build build-a -t install
      - run: brew install tree
        if: matrix.os == 'macOS-latest'
      - run: tree install
      - run: python -m pip install --user -U pip
      - run: python -m pip install --user cmeel-tinyxml
      - run: CMAKE_PREFIX_PATH=install:$(python -m cmeel cmake) cmake -B build-b -S b
      - run: cmake --build build-b
      - run: cmake --build build-b -t test
